### ISSUE TITLE
undefined is not a function

### ISSUE THREAD

**Issue by r115** [unindented/grunt-electron-windows-installer#1] opened 2015-08-02 06:24 UTC
I have been trying this out and even with all configuration options provided I keep running into 'undefined is not a function' error.

Better error reporting maybe so one can get an idea what could be off. 

Building on Win 7 32-bit. Nuget and Squirrel are installed correctly.

**Comment by unindented** [comment] 2015-08-02 12:30
@nandwabee Sorry about that. I thought I had enough error reporting...

Can you publish a small sample project on GitHub where I can reproduce the error?

**Comment by unindented** [comment] 2015-08-06 06:53
@nandwabee Did you figure out what the problem was?

**Comment by unindented** [comment] 2015-10-18 10:30
Closing issue as I don't have enough information to repro.

**Closed as completed by unindented** 2015-10-18 10:30 UTC
